# Очередь сообщений
number_message_queue = 1

# Параметры создания (create)
[create]
mean = 500
stddev = 50

# Станции: каждая в своей секции
[station 1]
type = 0
handle.mean = 4500
handle.stddev = 100

[station 2]
type = 0
handle.mean = 6500
handle.stddev = 100

[station 3]
type = 1
handle.mean = 3500
handle.stddev = 100

[station 4]
type = 1
handle.mean = 2500
handle.stddev = 100

[station 5]
type = 2
handle.mean = 5500
handle.stddev = 100
